### ISSUE TITLE
603쪽에서 keytool 실행 시 오류가 발생합니다.

### ISSUE THREAD

**Issue by Kateeeeeeeeeeee** [codefactory-co/golden-rabbit-flutter-novice#2]
참고 화면 공유드립니다.

![image](https://github.com/codefactory-co/golden-rabbit-flutter-novice/assets/108747690/66041162-b32c-42c3-9eea-0ac9bbc787f3)

**Comment by serendipity1004** [comment]
안녕하세요! 여기에 이슈를 올릴거라고 생각도 못해서 이제야 봤네요 ㅠㅠ 추후 도움은 저희 커뮤니티에서 요청하시면 더 빨리 도움을 받을 수 있습니다.
https://links.codefactory.ai
감사합니다!
